// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuQLosY6rtWFKhIg5JdqJoVraAid0-oJA',
    appId: '1:168364402816:web:42d0fc6e927178536b5e65',
    messagingSenderId: '168364402816',
    projectId: 'watchful-incident-app',
    authDomain: 'watchful-incident-app.firebaseapp.com',
    storageBucket: 'watchful-incident-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3G2juSyThyEF_2jIH0BsF3WKb_e8bIw',
    appId: '1:168364402816:android:6ddc75dc0f770aed6b5e65',
    messagingSenderId: '168364402816',
    projectId: 'watchful-incident-app',
    storageBucket: 'watchful-incident-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG440Io0QqJUZSqxQBQ68nyjyyROVj3SI',
    appId: '1:168364402816:ios:54c8b19a66df8d5e6b5e65',
    messagingSenderId: '168364402816',
    projectId: 'watchful-incident-app',
    storageBucket: 'watchful-incident-app.appspot.com',
    iosClientId: '168364402816-g4phjbedsqnrjhu56a2t1974ikdhjvec.apps.googleusercontent.com',
    iosBundleId: 'com.zatro.watchful',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG440Io0QqJUZSqxQBQ68nyjyyROVj3SI',
    appId: '1:168364402816:ios:54c8b19a66df8d5e6b5e65',
    messagingSenderId: '168364402816',
    projectId: 'watchful-incident-app',
    storageBucket: 'watchful-incident-app.appspot.com',
    iosClientId: '168364402816-g4phjbedsqnrjhu56a2t1974ikdhjvec.apps.googleusercontent.com',
    iosBundleId: 'com.zatro.watchful',
  );
}
